### ISSUE TITLE
Getting error "Cannot call method 'url' of undefined"

### ISSUE THREAD

**Issue by hassanabidpk** [ParsePlatform/Anyimg#7]
How to solve this issue.

More logs here 

 Result: TypeError: cloud/views/home.ejs:20
    18|   <% _(images).each(function(image) { %>
    19|     <div>
 >> 20|       <a href="/i/<%= image.id %>"><img src="<%= image.get('thumb').url() %>" /></a>
    21|     </div>
    22|   <% }); %>
    23| </div>

Cannot call method 'url' of undefined
    at eval (eval at <anonymous> (ejs.js:256:12), <anonymous>:29:603)
    at Function.T.each.T.forEach (underscore.js:17:714)
    at T.(anonymous function) [as each] (underscore.js:17:11738)
    at eval (eval at <anonymous> (ejs.js:256:12), <anonymous>:29:430)
    at ejs.js:261:15
    at Object.exports.render (ejs.js:299:13)
    at View.exports.renderFile [as engine] (ejs.js:325:22)
    at View.render (express_view.js:77:8)
    at Function.app.render (express_application.js:516:10)
    at res.render (express_response.js:763:7)

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
